# Generated by Django 3.2.18 on 2023-04-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_role',
            field=models.TextField(blank=True, default='New employee'),
        ),
    ]
