# Generated by Django 3.2.18 on 2023-04-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_pack_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='pack_description',
            field=models.TextField(),
        ),
    ]
