# Generated by Django 3.2.18 on 2023-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('LOGIN', 'Login issue'), ('REPORT_POST', 'Report a post'), ('GENERAL', 'General Enquiry'), ('DELETE_ACCOUNT', 'Delete Account')], default='GENERAL', max_length=255),
        ),
    ]
