# Generated by Django 3.2.18 on 2023-04-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20230410_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
