# Generated by Django 3.2.18 on 2023-04-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20230412_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_on']},
        ),
    ]
