# Generated by Django 3.2.18 on 2023-04-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
    ]
