# Generated by Django 3.2.18 on 2023-04-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='files',
        ),
    ]
