# Generated by Django 3.2.18 on 2023-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_task_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('NOT-STARTED', 'Not started'), ('IN-PROGRESS', 'In-progress'), ('COMPLETE', 'Complete')], default='NOT-STARTED', max_length=255),
        ),
    ]
